service:
  enabled: true
  serviceType: LoadBalancer
  port: 9001
  targetPort: 8081
  nodePort: 30103
  ingress:
    enabled: true
    paths:
      - /post
      - /post/draft
      - /post/*
      - /post/*/like
      - /likes/*
      - /post/*/reply
      - /reply
      - /reply/*/like
      - /report/post
      - /report/reply
      - /share
      - /share/*
      - /posts
      - /posts/*/rss
      - /follow-posts/*
      - /follows/*
      - /followers/*
      - /suggested-follows/*
      - /follow
      - /follow/*
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 500m
  env:
    KAFKA_BOOTSTRAP_SERVERS: thirdplace-kafka-kafka-brokers.kafka.svc.cluster.local
    KAFKA_SECURITY_PROTOCOL:
    KAFKA_SASL_MECHANISM:
    KAFKA_SASL_USERNAME:
    KAFKA_SASL_PASSWORD:

    POSTGRES_HOST: community-service-postgres.community-service.svc.cluster.local
    POSTGRES_PORT: 5432
    POSTGRES_DBNAME: community_service
    POSTGRES_USER: service_user
postgres:
  auth:
    username: service_user
    database: community_service
