service:
  enabled: true
  port: 9001
  targetPort: 8081
  ingress:
    enabled: true
    paths:
#      - /post
#      - /post/draft
#      - /post/*
#      - /post/*/like
#      - /likes/*
#      - /post/*/reply
#      - /reply
#      - /reply/*/like
#      - /report/post
#      - /report/reply
#      - /share
#      - /share/*
      - /posts
#      - /posts/*/rss
#      - /follow-posts/*
#      - /follows/*
#      - /followers/*
#      - /suggested-follows/*
#      - /follow
#      - /follow/*
  secrets:
    POSTGRES_PASSWORD: AgBkbbySvZLWJKm+K61FNa+9WQW+g/kvwhLdoM3Rr3K0CXmKaKGBDlF3QYHIQqlhYZpJ9xvsIUJMRcXo6MQc54HnpltZoxkuejLVPSLUfxoOsyANZBlo/ze7LnSn9mLqh2Rn8LtIPEDF2mqGV+LNgRX+04Sk60s8pdg1akoFXUBOm0Ln4gmvY7wPL1zJ7KiKeaf4Fq4j/IJfdC/VtrCx+5ROysAYwlnZ7dWflXqXKRPrk/fco8JXYRc5FdYeF7rINbKJWWmQcnmKCtxlmMzyiUJTtRbv7wp6CdP5E+D1mFmlaHxMfs2j5/ULA3mh3FuUHqGatuWXADMQV6H7voyIwVksF6oSJIj/DCINsiQWHbwWOxK9lclcDzG4zowdaQoIBUxWMHOaiKRAMNxGFY5Z3wTBYrJlNe9gGlbZ7uKxt4FABlJVPJzEz63bfEk+Ev2AwP67rUVNTv6pADF8NsXzSKmlCIBb9Jnth3uXzQ80sqXuJIsqwngIH1oLR733GCrg2/0lGN3d1+QYxY6T1v70JkOrhvblQcCpk7IqpqfJTxyd8BQsO2HD9OG2j/XFsCPaJCIKFD04/971ABQlCraI5D4+GKHLsSDYOhzGWogwEL96oEols26Z4rG3lNkjAsqVBd9P0OJMHf5BGvEwdOWFdxRFe33oOlshRgW2ZHwIidN2MGGb0l1xK7Nz2RWRNrDhb0klQC5KrKrKgU+KVJAYLHlSUsh63tkW3jE=
    JWT_KEY: AgApJhTFwHdD2XADemV11Zq0m72iwRbQbSwp8pBU7x478pKmkCt/XEYqUajkazw1B94mdAj2P7ilZht3cISSdidGWQAGFvRGPHb3BIANzz1iTFjvzdRF5g0c5cByYaxF4p7dNQLeeVidQFUXLcUCfznXcAI4KFXuJYRY/CSwHfhnM2P5d9uGgW38c3QjSwJql9Cy5Nw2mRlXgq11eBhVGKHULYD6VfMFcGZsVkr3bmdxF0lZtme2L8+UXQrlSjgDxkXzQEN7qJ7/KqMtcFrqZmWEoH3T0XQ4FWSAnLk1eyfF9ksbB88CDWEhZPJyh5zGnQpFCRDMnzYeVaXr39iwwr7f1SusPe7pYNyBW14h5tZWfqkA5aWmFl7wra+uyNRcbuqOYqsF0+9lfH5ZkhClO5hHwK/MVpOXgF+mvIonI2CItfFtrcQasWSgxMHnAb2pW1/J6gTcBqCbh/NtFUqySfbQX1z1yA2saRMN2uYTIEc9ecB+XBcVpF4magJcnoNzJ5RGvL4suNGWSTNEkE7m8HSBd5uCuU7w+n1ydCZljkN/W3EGpDWwz87ejVVHmQ2nngt06Np5eQyvZJHcqhe+QOjHM6DR1HwsM6AhDXfi28P7oNrFnMHgVm+Eb8M3IvK73PmJUdxTIj1z4aoc74yHadg0PF7F8mQpc9l8mqJGQBo5S7sFROrAENNeDgN23Av5n3DOOlikkEr4R1kgzyEKhq89E9o9Asa6Ej7ktyWLGAKIY3/agNL7/3ONPK9HfODDC3Fiuf17BXimB0AAHbO+0aRy
  env:
    KAFKA_BOOTSTRAP_SERVERS: thirdplace-kafka-kafka-bootstrap.kafka.svc.cluster.local
    KAFKA_SECURITY_PROTOCOL:
    KAFKA_SASL_MECHANISM:
    KAFKA_SASL_USERNAME:
    KAFKA_SASL_PASSWORD:

    POSTGRES_HOST: community-service-postgres.community-service.svc.cluster.local
    POSTGRES_PORT: 5432
    POSTGRES_DBNAME: community_service
    POSTGRES_USER: service_user
postgres:
  auth:
    username: service_user
    database: community_service
