/*
 * Otto user service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

import (
	"encoding/json"
	"net/http"
)

type NewReply struct {
	Post Post `json:"post"`

	Text string `json:"text"`
}

func DecodeRequestToNewReply(r *http.Request) *NewReply {
	decoder := json.NewDecoder(r.Body)
	var data *NewReply
	err := decoder.Decode(&data)
	if err != nil {
		panic(err)
	}
	return data
}
