/*
 * Otto user service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

type NewReplyReport struct {
	Text string `json:"text,omitempty"`

	User User `json:"user"`

	Reply Reply `json:"reply"`
}
