/*
 * Otto user service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

import (
	"github.com/google/uuid"
	"time"
)

type Reply struct {
	Uuid string `json:"uuid"`

	CreatedAt time.Time `json:"created_at,omitempty"`

	Post Post `json:"post"`

	Text string `json:"text"`

	Likes uint `json:"likes"`

	SelfLiked bool `json:"selfLiked,omitempty"`

	User User `json:"user"`
}

func CreateReply(postUuid *uuid.UUID, replyUserUuid *uuid.UUID, message string) *Reply {
	return &Reply{
		Text: message,
		Post: Post{
			Uuid: postUuid.String(),
		},
		User: User{
			Uuid: replyUserUuid.String(),
		},
	}
}

func CreateNewReply(postUuid *uuid.UUID, message string) *NewReply {
	return &NewReply{
		Text: message,
		Post: Post{
			Uuid: postUuid.String(),
		},
	}
}
