/*
 * Otto user service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

type ReplyLike struct {
	Uuid string `json:"uuid"`

	Post Reply `json:"post,omitempty"`

	User User `json:"user"`
}
