/*
 * Otto user service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

import (
	"time"
)

type ReplyReport struct {
	Uuid string `json:"uuid"`

	CreatedAt time.Time `json:"created_at,omitempty"`

	Reporter User `json:"reporter"`

	User User `json:"user,omitempty"`

	Text string `json:"text,omitempty"`

	Reply Reply `json:"reply"`
}
