/*
 * Otto user service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

import (
	"time"
)

type Share struct {
	Uuid string `json:"uuid"`

	CreatedAt time.Time `json:"created_at,omitempty"`

	Text string `json:"text,omitempty"`

	SelfLiked bool `json:"selfLiked,omitempty"`

	User User `json:"user"`

	Post Post `json:"post"`
}
