apiVersion: v1
kind: Service
metadata:
  name: community-service
spec:
  type: ClusterIP
  selector:
    app: community-service
  ports:
    - name: http
      port: 8081
      protocol: TCP
      targetPort: http
